apiVersion: enterprisesearch.k8s.elastic.co/v1
kind: EnterpriseSearch
metadata:
  name: enterprise-search-elasticsearch
  namespace: elastic
spec:
  version: 8.10.4
  count: 1
  elasticsearchRef:
    name: elasticsearch